import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
To view the source, visit the repository for this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Embeds .py files as plain text strings so the Python PTY bridge
// is bundled into main.js without needing node_modules at runtime.
const pythonTextPlugin = {
	name: "python-text",
	setup(build) {
		build.onLoad({ filter: /\.py$/ }, (args) => {
			const text = fs.readFileSync(args.path, "utf8");
			return { contents: `export default ${JSON.stringify(text)}`, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [pythonTextPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
